### ISSUE TITLE
SMT doesn't function anymore after recent C&C3 KW patch

### ISSUE THREAD

**Issue by cas-giepmans** [MetaIdea/SageMetaTool#10]
In-game functions of SMT are not available. The overlay and skirmish config are also gone.

**Comment by cas-giepmans** [comment]
Files that were changed in the recent patch: https://steamdb.info/patchnotes/13579547/

**Comment by GarTheConquer** [comment]
Same here. Like SMT isn't even there.

**Comment by cas-giepmans** [comment]
I solved it by using compatibility exe's for both tibwars and kw, which can be downloaded through the media fire link in one of the two documents that comes with the smt download.

**Comment by GarTheConquer** [comment]
Any advice for SMT (not activating) for Kane's Wrath Steam Edition?

**Comment by MetaIdea** [comment]
Just wait a bit for the new SMT update coming soon.
