### ISSUE TITLE
Multiplayer Kanes Wrath/RA3

### ISSUE THREAD

**Issue by GodMeyo** [MetaIdea/SageMetaTool#2]
Yo MetaIdea,

strongly interested in your work but for the simple reason to enjoy those titles in multiplayer at 60 FPS as the 30 FPS cap is the single reason to hold me from still playing this.

Did you come to test it with another user?

**Comment by MetaIdea** [comment]
Yes latest version 0.54 now has multiplayer and network support for all players that also use the tool. The 60 fps mode for TW/KW now reached a promising state.
