### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by JSheffield159** [MetaIdea/SageMetaTool#3]
I'm a bit confused how to download SMT, the link you have is direct to your Patreon but that is locked behind a Patreon only post.

https://www.patreon.com/posts/53702342
--> https://www.patreon.com/posts/63086858

Could you make this download link public?

Cheers!

**Comment by Yardanico** [comment]
AFAIK SageMetaTool is paid-only, so you have to donate to Patreon to get it.
