### ISSUE TITLE
Shortcuts for camera tilting (NumPad 1 and 3) don't work with Tiberium Wars

### ISSUE THREAD

**Issue by rezss** [MetaIdea/SageMetaTool#7]
The shortcuts for the camera tilting won't with with Tiberium Wars. The slider in the menu works fine though.
The camera zoom and angle is reset after the "incoming transmission" in the campaign, however. Would be appreciated if you could fix that also.

**Comment by MetaIdea** [comment]
Zoom will be enforced now if campaign scripts try to verwrite it
