### ISSUE TITLE
SMT button position on top of minimap with 32:9 aspect ratio

### ISSUE THREAD

**Issue by rezss** [MetaIdea/SageMetaTool#8]
The SMT buttons are unfortunately on top of the minimap on a resolution like 5120x1440. Would be appreciated of the position of the buttons could either be configured, or disabled all together since the shortcuts to access them work just fine.

![image](https://github.com/MetaIdea/SageMetaTool/assets/2461029/a2de3f40-a1b3-4198-99d6-3d661155498d)

**Comment by MetaIdea** [comment]
You can now hide the button with M key.
